### ISSUE TITLE
Config is getting reset after every import

### ISSUE THREAD

**Issue by nullmonk** [RITRedteam/Sangheili#5]
Somehow make a global config or maybe just load the config file for every module.

This is evident in `networking.py` when trying to set how many devices to discover

**Comment by KoalaTea** [comment]
dont import with from src import config or from . import config. instead do import src and reference config as src.config, this has to do with how pointers and module level variables work in python.

**Comment by KoalaTea** [comment]
https://github.com/RITRedteam/Sangheili/blob/master/sangheili.py#L21

I believe this line is not actually editing what is in src.__init__.py and not changing that config object but instead instantiating a new dict object and setting the config variable in sangheili to point to that object, while before hand it was pointing to the memory address of the config variable in src.__init__.py

**Comment by nullmonk** [comment]
Fixed in #7
